name: C/C++ CI

on:
  push:
    branches: [ "divider" ]
  pull_request:
    branches: [ "divider" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Упростил - убрал matrix
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Google Test
      run: |
        sudo apt-get update
        sudo apt-get install -y googletest libgtest-dev build-essential
        # Устанавливаем Google Test в систему
        sudo apt-get install -y libgtest-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib
        
    - name: make
      run: make
      
    - name: Test
      id: test
      run: |
        chmod +x device
        ./device

    - name: Calculate code coverage
      id: covr
      run: |
        sudo apt install -y gcovr
        g++ --coverage -g -O0 -fprofile-arcs -ftest-coverage -I/usr/include/gtest -L/usr/lib/x86_64-linux-gnu device.cpp -lgtest -lpthread -o test_executable
        chmod +x ./test_executable
        ./test_executable
        gcovr --xml coverage.cobertura.xml

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
    
    - name: Get the coverage
      id: get_coverage
      run: |
        cat code-coverage-results.md
        COVVALUE="$(grep 'Summary' code-coverage-results.md | awk '{print $3}' | tr -d \*)"
        echo "COVERAGE=$COVVALUE" >> $GITHUB_ENV
    
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: "0062b412a085249828efa9ad60c6d21e"
        filename: lab_device_main.json
        label: Test Coverage
        message: ${{ env.COVERAGE }}
        color: green
